export default {
  BritishAirwaysLogo: require('../assets/images/BritishAirwaysLogo.png'),
  EmiratesLogo1985: require('../assets/images/EmiratesLogo1985.jpeg'),
  Flight: require('../assets/images/Flight.png'),
  Twtr: require('../assets/images/Twtr.png'),
  Ig: require('../assets/images/Ig.png'),
  Fb: require('../assets/images/Fb.png'),
  Telgrm: require('../assets/images/Telgrm.png'),
  Paypal: require('../assets/images/Paypal.png'),
  GooglePay: require('../assets/images/GooglePay.png'),
  ApplePay: require('../assets/images/ApplePay.png'),
  Mcard: require('../assets/images/Mcard.png'),
  ChannelBanner: require('../assets/images/ChannelBanner.png'),
  ChannelDP: require('../assets/images/ChannelDP.png'),
  Discord: require('../assets/images/Discord.png'),
  Yt: require('../assets/images/Yt.png'),
  LastStream: require('../assets/images/LastStream.png'),
  Games: require('../assets/images/Games.png'),
  Video: require('../assets/images/Video.png'),
  Buin1: require('../assets/images/Buin1.png'),
  Buin2: require('../assets/images/Buin2.png'),
  Buin3: require('../assets/images/Buin3.png'),
  Buin4: require('../assets/images/Buin4.png'),
  Buin7: require('../assets/images/Buin7.png'),
  Mark: require('../assets/images/Mark.png'),
};
